<?php

namespace Database\Seeders;

use App\Models\ConceptoCatalogo;
use App\Models\TarifaServiciosDetalle;
use App\Models\TipoToma;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConceptoCatalogoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        /*
        DB::table('concepto_catalogos')->insert([
            [
                'nombre' => 'Servicio de agua potable',
                'descripcion' => 'Aqui se describe el agua potable',
                'prioridad_abono' => '1',
                'estado' => 'activo',
            ],
            [
                'nombre' => 'Servicio de alcantarillado',
                'descripcion' => 'Aqui se describe el alcantarillado',
                'prioridad_abono' => '1',
                'estado' => 'activo',
            ],
            [
                'nombre' => 'Tratamiento y saneamiento',
                'descripcion' => 'Aqui se describe el tratamiento y el sanemianto',
                'prioridad_abono' => '1',
                'estado' => 'activo',
            ],
            [
                'nombre' => 'Multas',
                'descripcion' => 'Descripcion de la multa',
                'prioridad_abono' => '2',
                'estado' => 'activo',
            ],
            [
                'nombre' => 'Costo contrato de agua potable',
                'descripcion' => 'Descripcion del costo del contrato de agua',
                'prioridad_abono' => '1',
                'estado' => 'activo',
            ],
            [
                'nombre' => 'Costo contrato de alcantarillado',
                'descripcion' => 'Descripcion del costo del contrato de alcantarillado',
                'prioridad_abono' => '1',
                'estado' => 'activo',
            ],
            [
                'nombre' => 'Reconexion de agua',
                'descripcion' => 'Descripcion del costo de la reconexion',
                'prioridad_abono' => '3',
                'estado' => 'activo',
            ],
            [
                'nombre' => 'Constancia de factibilidad de agua',
                'descripcion' => 'Descripcion del costo de la factibilidad',
                'prioridad_abono' => '4',
                'estado' => 'activo',
            ],
            [
                'nombre' => 'Constancia de no servicio',
                'descripcion' => 'Descripcion de no servicio',
                'prioridad_abono' => '4',
                'estado' => 'activo',
            ],
            [
                'nombre' => 'Constancia de servicio',
                'descripcion' => 'Descripcion de no servicio',
                'prioridad_abono' => '5',
                'estado' => 'activo',
            ],
            [
                'nombre' => 'Profundidad',
                'descripcion' => 'Descripcion de la profundidad',
                'prioridad_abono' => '5',
                'estado' => 'activo',
            ],
        ]);*/

        DB::table('tarifas')->insert([
            [
                'nombre' => 'TARIFA JULIO 2024',
                'descripcion' => 'ninguna',
                'fecha' => now(),
                'estado' => 'activo',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);

        $tipo_tomas = TipoToma::all();
        $tipo_tomas->each(function ($tipo_toma) {
            $rango = 17;
            for ($i = 1; $i <= 10; $i++) {
                TarifaServiciosDetalle::factory()->create([
                    'id_tarifa' => 1,
                    'id_tipo_toma' => $tipo_toma->id,
                    'rango' => $rango * $i,
                    'agua' => 10 * 17,
                    'alcantarillado' => 2 * 17,
                    'saneamiento' => 2 * 17
                ]);
            }
        });

        //ConceptoCatalogo::factory()->count(10)->create();
        $conceptos = [
            [
                "nombre" => "SERVICIO DE AGUA POTABLE",
                "descripcion" => "Servicio de suministro de agua potable.",
                "estado" => "activo",
                "categoria" => 'todas',

                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "SERV. ALCANTARILLADO",
                "descripcion" => "Servicio de alcantarillado.",
                "estado" => "activo",
                "categoria" => 'todas',
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "TRAT. Y SANEAMIENTO",
                "descripcion" => "Servicio de tratamiento y saneamiento.",
                "estado" => "activo",
                "categoria" => 'todas',
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "REZ. SERVICIO DE AGUA POTABLE",
                "descripcion" => "Rezago en el servicio de agua potable.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "REZAGO ALCANTARILLADO",
                "descripcion" => "Rezago en el servicio de alcantarillado.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "REZ. TRAT.Y SANEAMI",
                "descripcion" => "Rezago en el servicio de tratamiento y saneamiento.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "IMP.RECUPER. ELECTR.",
                "descripcion" => "Impuesto de recuperación eléctrica.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "REZ.RECUPER. ELECTR.",
                "descripcion" => "Rezago en la recuperación eléctrica.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "I.V.A.",
                "descripcion" => "Impuesto al Valor Agregado.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "IMPORTE RECARGOS.",
                "descripcion" => "Importe de recargos.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "REZAGO DE RECARGOS.",
                "descripcion" => "Rezago en recargos.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "APORTACIONES",
                "descripcion" => "Aportaciones.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONVENIOS X CONSUMO",
                "descripcion" => "Convenios por consumo.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "MULTAS.",
                "descripcion" => "Multas.",
                "estado" => "activo",
                "prioridad_abono" => 1,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 0,
                "tarifa_fija" => 0,
            ],
            [
                "nombre" => "ADEL. A CONV. X CONS.",
                "descripcion" => "Adelanto a convenio por consumo.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "RECONEXION DE AGUA",
                "descripcion" => "Reconexión de agua.",
                "estado" => "activo",
                "prioridad_abono" => 1,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 0,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "Convenio.CONT. AGUA POT.",
                "descripcion" => "Convenio de continuidad de agua potable.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "Convenio.CONT. ALCANTAR.",
                "descripcion" => "Convenio de continuidad de alcantarillado.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "NOTIFICACION REZAGO",
                "descripcion" => "Notificación de rezago.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "RECUP. COLECTOR SUR",
                "descripcion" => "Recuperación del colector sur.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "INGRESO X RECIBOS IMPRESOS",
                "descripcion" => "Ingreso por recibos impresos.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CISTERNA O TINACO",
                "descripcion" => "Compra de cisterna o tinaco.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "10% ANTICIPO DE CISTERNA O TINACO",
                "descripcion" => "10% de anticipo para la compra de cisterna o tinaco.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "COBRO DE MILLARES",
                "descripcion" => "Cobro por millares.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "INGRESO DE APORTACIONES FEDERALES",
                "descripcion" => "Ingreso de aportaciones federales.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONSUMO DE PIPAS",
                "descripcion" => "Consumo de pipas de agua.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONSUMO ESTIMADO",
                "descripcion" => "Consumo estimado de servicios.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "DESASOLVE DE FOSAS SEPTICA",
                "descripcion" => "Servicio de desasolve de fosas sépticas.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "RECARGOS",
                "descripcion" => "Recargos por servicios.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CAMBIO O REP. MEDIDOR",
                "descripcion" => "Cambio o reparación de medidor.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "RECONEXION DE DRENAJE",
                "descripcion" => "Reconexión de drenaje.",
                "estado" => "activo",
                "prioridad_abono" => 1,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CAMBIO DE PROPIETARIO",
                "descripcion" => "Cambio de propietario del servicio.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "COSTO CONTRATO AGUA POTABLE",
                "descripcion" => "Costo del contrato de agua potable.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "COSTO CONTRATO ALCANTARILLADO",
                "descripcion" => "Costo del contrato de alcantarillado.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "DERECHOS DE CONEXION AGUA POTABLE",
                "descripcion" => "Derechos de conexión de agua potable.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "DERECHOS DE CONEXION ALCANT.",
                "descripcion" => "Derechos de conexión de alcantarillado.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "OTROS INGRESOS",
                "descripcion" => "Otros ingresos diversos.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "RECUPERACION DE OBRA",
                "descripcion" => "Recuperación de obra.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONSTANCIA DE NO ADEUDO",
                "descripcion" => "Constancia de no adeudo.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "NOTIFICACION",
                "descripcion" => "Notificación de servicio.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "ROTURA Y BACHEO DE PAVIMENTO",
                "descripcion" => "Servicio de rotura y bacheo de pavimento.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "VENTA DE AGUA TRATADA",
                "descripcion" => "Venta de agua tratada.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONSTANCIA DE FACTIBILIDAD DE AGUA",
                "descripcion" => "Constancia de factibilidad de agua.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONSTANCIA DE FACTIBILIDAD DE ALCANTARILLADO Y SANEAMIENTO",
                "descripcion" => "Constancia de factibilidad de alcantarillado y saneamiento.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "PAGO POR DESCARGA DE AGUAS RESIDUALES",
                "descripcion" => "Pago por descarga de aguas residuales.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "VENTA DE ACTIVO",
                "descripcion" => "Venta de activos.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "REINTEGRO DE DERECHO CNA",
                "descripcion" => "Reintegro de derecho CNA.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "compra de bases de licitación",
                "descripcion" => "Compra de bases de licitación.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CAMBIO DE RED",
                "descripcion" => "Cambio de red de servicios.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "PAGO POR REPARACION DE DAÑOS",
                "descripcion" => "Pago por reparación de daños.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "TRAT. Y SANEAMIENTO",
                "descripcion" => "Tratamiento y saneamiento de aguas.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "VENTA DE AGUA EN BLOCK",
                "descripcion" => "Venta de agua en bloque.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "RECUPERACION DEL BURO DE CREDITO",
                "descripcion" => "Recuperación del buró de crédito.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "SUPERVISION DE INFRAESTRUCTURA",
                "descripcion" => "Supervisión de infraestructura.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "REGISTRO A LA RED SANITARIA",
                "descripcion" => "Registro a la red sanitaria.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "MILLARES P/DESARROLLADORES DE VIVIENDA",
                "descripcion" => "Millares para desarrolladores de vivienda.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "COMISIONES S/CHEQUE DEVUELTO",
                "descripcion" => "Comisiones sobre cheques devueltos.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "VENTAS DE TINACOS",
                "descripcion" => "Ventas de tinacos.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "INTERESES MORATORIOS",
                "descripcion" => "Intereses moratorios.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "DESCUENTO POR PRONTO PAGO",
                "descripcion" => "Descuento por pronto pago.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "PAGO POR REPARACION DE DAÑOS",
                "descripcion" => "Pago por reparación de daños.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "RECONEXION",
                "descripcion" => "Reconexión de servicios.",
                "estado" => "activo",
                "prioridad_abono" => 1,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CARGO EN CAJA",
                "descripcion" => "Cargo en caja.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "ABONO EN CAJA",
                "descripcion" => "Abono en caja.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 0,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "PAGO EN CAJA",
                "descripcion" => "Pago en caja.",
                "estado" => "activo",
                "prioridad_abono" => 15,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "DESCUENTO POR REDONDEO",
                "descripcion" => "Descuento por redondeo.",
                "estado" => "activo",
                "prioridad_abono" => 15,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CARGO POR REDONDEO",
                "descripcion" => "Cargo por redondeo.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "INTERESES",
                "descripcion" => "Intereses generados.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "RECARGOS DEL MES",
                "descripcion" => "Recargos del mes en curso.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "PAGO ANTICIPADO",
                "descripcion" => "Pago anticipado de servicios.",
                "estado" => "activo",
                "prioridad_abono" => 15,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CANCELACION DE PAGO",
                "descripcion" => "Cancelación de pago.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "BONIFICACION POR ERROR DE CARGO",
                "descripcion" => "Bonificación por error de cargo.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 0,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "ABONO POR GENERACION DE CONVENIO",
                "descripcion" => "Abono por generación de convenio.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 0,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "INCUMPLIMIENTO DE PAGO DE LETRAS",
                "descripcion" => "Incumplimiento de pago de letras.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "ANTICIPO DE CONVENIO",
                "descripcion" => "Anticipo de convenio.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "LETRA DE CONVENIO",
                "descripcion" => "Letra de convenio.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "AJUSTE EN CONVENIOS",
                "descripcion" => "Ajuste en convenios.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 0,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "PAGO LETRA",
                "descripcion" => "Pago de letra.",
                "estado" => "activo",
                "prioridad_abono" => 15,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CARGO A EMPLEADO POR FALTANTE EN CAJA",
                "descripcion" => "Cargo a empleado por faltante en caja.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "BONIFICACIÓN",
                "descripcion" => "Bonificación por diversos motivos.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 0,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "ABONO POR RECLASIFICACION DE ADEUDO",
                "descripcion" => "Abono por reclasificación de adeudo.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 0,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "ABONO POR CANCELACION DE CONVENIO",
                "descripcion" => "Abono por cancelación de convenio.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 0,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "BONIFICACION POR DESAUTORIZACION DE SOLICITUD",
                "descripcion" => "Bonificación por desautorización de solicitud.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 0,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "BONIFICACION POR CANCELACION DE SOLICITUD",
                "descripcion" => "Bonificación por cancelación de solicitud.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 0,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "AJUSTE",
                "descripcion" => "Ajuste por diversos motivos.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 0,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "ADEUDO ANTERIOR",
                "descripcion" => "Adeudo anterior.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 0,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "VENTA AGUA EN PIPAS",
                "descripcion" => "Venta de agua en pipas.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 0,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "Descarga Atarjeas",
                "descripcion" => "Descarga en atarjeas.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "Descarga Atarjeas Saneamiento",
                "descripcion" => "Descarga en atarjeas para saneamiento.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CARGO POR ERROR DE PAGO A USUARIO",
                "descripcion" => "Cargo por error de pago a usuario.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "ELECTRICIDAD",
                "descripcion" => "Consumo de electricidad.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 0,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "TIPO DE SUELO",
                "descripcion" => "Tipo de suelo.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "EXCEDENTE DE MATERIAL",
                "descripcion" => "Excedente de material.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "MULTA POR FALTA DE CONTRATO",
                "descripcion" => "Multa por falta de contrato.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "Conv. Agua purificada",
                "descripcion" => "Convenio de agua purificada.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 0,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONSTANCIA DE contrato RECIENTE",
                "descripcion" => "Constancia de contratación reciente.",
                "estado" => "activo",
                "categoria" => 'contrato',
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "COSTO POR SUSPENCION TEMPORAL SERV. AGUA",
                "descripcion" => "Costo por suspensión temporal del servicio de agua.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "COSTO POR SUSPENCION TEMPORAL SERV. ALCANTARILLADO",
                "descripcion" => "Costo por suspensión temporal del servicio de alcantarillado.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "ROMPIMIENTO DE BANQUETA (ML)",
                "descripcion" => "Rompimiento de banqueta (metro lineal).",
                "estado" => "activo",
                "categoria" => 'contrato',
                "tipo_tarifa" => 'ML',
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 0,
            ],
            [
                "nombre" => "SERVICIO DE AGUA (JURIDICO)", ////COMO QUE JURIDICO
                "descripcion" => "Servicio de agua en ámbito jurídico.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "ALCANTARILLADO SANITARIO (JURIDICO)", /////SERVICIO DE DRENAJE PAL MAGISTERIO????
                "descripcion" => "Alcantarillado sanitario en ámbito jurídico.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "SANEAMIENTO Y TRATAMIENTO (JURIDICO)",
                "descripcion" => "Saneamiento y tratamiento en ámbito jurídico.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO AGUA 1/2\"  COMUN 9M.",
                "descripcion" => "Contrato de agua 1/2\" común a 9 metros.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO AGUA 1/2\" MATERIAL III",
                "descripcion" => "Contrato de agua 1/2\" material tipo III.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO AGUA 3/4\" COMUN",
                "descripcion" => "Contrato de agua 3/4\" común.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO AGUA 3/4\" MATERIAL III",
                "descripcion" => "Contrato de agua 3/4\" material tipo III.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO AGUA 1\" COMUN",
                "descripcion" => "Contrato de agua 1\" común.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO AGUA 1\" MATERIAL III",
                "descripcion" => "Contrato de agua 1\" material tipo III.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO AGUA CON PREP. 1/2\"",
                "descripcion" => "Contrato de agua con preparación 1/2\".",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO AGUA 1/2\" CON CUADRO",
                "descripcion" => "Contrato de agua 1/2\" con cuadro.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO AGUA CON PREP. 3/4\"",
                "descripcion" => "Contrato de agua con preparación 3/4\".",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO AGUA 3/4\" CON CUADRO",
                "descripcion" => "Contrato de agua 3/4\" con cuadro.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO AGUA CON PREP. 1\"",
                "descripcion" => "Contrato de agua con preparación 1\".",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO AGUA 1\" CON CUADRO",
                "descripcion" => "Contrato de agua 1\" con cuadro.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO AGUA CON PREP. Y CUADRO, COL. MARQUEZ",
                "descripcion" => "Contrato de agua con preparación y cuadro, Colonia Márquez.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO DRENAJE A 1.25M. (CUADRILLA) COMUN",
                "descripcion" => "Contrato de drenaje a 1.25 metros (cuadrilla) común.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO DRENAJE A 1.25M. (CUADRILLA)TIPO III",
                "descripcion" => "Contrato de drenaje a 1.25 metros (cuadrilla) tipo III.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO DRENAJE A 1.50M.(CUADRILLA)COMUN",
                "descripcion" => "Contrato de drenaje a 1.50 metros (cuadrilla) común.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO DRENAJE A 1.50M.(CUADRILLA)TIPO III",
                "descripcion" => "Contrato de drenaje a 1.50 metros (cuadrilla) tipo III.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO DRENAJE A 1.75M.(CUADRILLA)COMUN",
                "descripcion" => "Contrato de drenaje a 1.75 metros (cuadrilla) común.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO DRENAJE A 1.75M.(CUADRILLA) TIPO III",
                "descripcion" => "Contrato de drenaje a 1.75 metros (cuadrilla) tipo III.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO DRENAJE A 2.00M.(CUADRILLA)COMUN",
                "descripcion" => "Contrato de drenaje a 2.00 metros (cuadrilla) común.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO DRENAJE A 2.00M.(CUADRILLA)TIPO III",
                "descripcion" => "Contrato de drenaje a 2.00 metros (cuadrilla) tipo III.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO DRENAJE A 2.25M.(RETRO) COMUN",
                "descripcion" => "Contrato de drenaje a 2.25 metros (retroexcavadora) común.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO DRENAJE A 2.25M.(RETRO)TIPO III",
                "descripcion" => "Contrato de drenaje a 2.25 metros (retroexcavadora) tipo III.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO DRENAJE A 2.50M.(RETRO)COMUN",
                "descripcion" => "Contrato de drenaje a 2.50 metros (retroexcavadora) común.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO DRENAJE A 2.50M.(RETRO) TIPO III",
                "descripcion" => "Contrato de drenaje a 2.50 metros (retroexcavadora) tipo III.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO DRENAJE A 2.75M.(RETRO)COMUN",
                "descripcion" => "Contrato de drenaje a 2.75 metros (retroexcavadora) común.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO DRENAJE A 2.75M.(RETRO) TIPO III",
                "descripcion" => "Contrato de drenaje a 2.75 metros (retroexcavadora) tipo III.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO DRENAJE A 3.00M.(RETRO) COMUN",
                "descripcion" => "Contrato de drenaje a 3.00 metros (retroexcavadora) común.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO DRENAJE A 3.00M.(RETRO) TIPO III",
                "descripcion" => "Contrato de drenaje a 3.00 metros (retroexcavadora) tipo III.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CONTRATO DRENAJE CON PREPARACION",
                "descripcion" => "Contrato de drenaje con preparación.",
                "estado" => "activo",
                "categoria" => 'contrato',

                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "TIPO DE SUELO A (COMUN) ML ADICIONAL A 9M.",
                "descripcion" => "Tipo de suelo A (común) metro lineal adicional a 9 metros.",
                "estado" => "activo",
                "categoria" => 'contrato',
                "tipo_tarifa" => 'ML',
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 0,
            ],
            [
                "nombre" => "TIPO DE SUELO C (DE PIEDRA) ML ADICIONAL A 9M.",
                "descripcion" => "Tipo de suelo C (de piedra) metro lineal adicional a 9 metros.",
                "estado" => "activo",
                "categoria" => 'contrato',
                "tipo_tarifa" => 'ML',
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 0,
            ],
            [
                "nombre" => "ROMPIMIENTO DE PAVIMENTO ASFALTO (ML)",
                "descripcion" => "Rompimiento de pavimento de asfalto (metro lineal).",
                "estado" => "activo",
                "categoria" => 'contrato',
                "tipo_tarifa" => 'ML',
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 0,
            ],
            [
                "nombre" => "ROMPIMIENTO DE PAVIMENTO HIDRAULICO (ML)",
                "descripcion" => "Rompimiento de pavimento hidráulico (metro lineal).",
                "estado" => "activo",
                "categoria" => 'contrato',
                "tipo_tarifa" => 'ML',
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 0,
            ],
            [
                "nombre" => "CONSTANCIA DE NO SERVICIO",
                "descripcion" => "Constancia de no servicio.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "NOTIFICACION POR FALTA DE CONTRATO",
                "descripcion" => "Notificación por falta de contrato.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "ALTOS INDICES DE CONTAMINATES",
                "descripcion" => "Altos índices de contaminantes.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "correccion saldo migrado",
                "descripcion" => "Corrección de saldo migrado.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "Convenio 50%",
                "descripcion" => "Convenio con descuento del 50%.",
                "estado" => "activo",
                "prioridad_abono" => 2,
                "cargo_directo" => 0,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "CANCELACION DE CONVENIO",
                "descripcion" => "Cancelación de convenio.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "EXCEDENTE VOLUMEN DESCARGA",
                "descripcion" => "Excedente de volumen de descarga.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "AGUA RESIDUAL EL BLOQUE",
                "descripcion" => "Agua residual en el bloque.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "AGUA EN PIPAS SIN RED",
                "descripcion" => "Agua en pipas sin red.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 0,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "Aportación para infraestructura hidráulica",
                "descripcion" => "Aportación para infraestructura hidráulica.",
                "estado" => "activo",
                "prioridad_abono" => 3,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "Facturacion",
                "descripcion" => "Facturacion",
                "estado" => "activo",
                "categoria" => 'facturacion',

                "prioridad_abono" => 2,
                "prioridad_por_antiguedad" => 1,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 1,
                "tarifa_fija" => 1,
            ],
            [
                "nombre" => "Factibilidad y derechos de conexión",
                "descripcion" => "Cobro de la factibilidad y derechos de conexion",
                "estado" => "activo",
                "categoria" => 'factibilidad',

                "prioridad_abono" => 2,
                "prioridad_por_antiguedad" => 0,
                "cargo_directo" => 1,
                "genera_iva" => 1,
                "abonable" => 0,
                "tarifa_fija" => 0,
            ],
            [
                "nombre" => "Letra de convenio",
                "descripcion" => "Pago de letra por convenio",
                "estado" => "activo",
                "categoria" => 'todas',
                "prioridad_abono" => 1,
                "prioridad_por_antiguedad" => 1,
                "cargo_directo" => 1,
                "genera_iva" => 0,
                "abonable" => 0,
                "tarifa_fija" => 0,
            ],
            [
                "nombre" => "Constancia",
                "descripcion" => "Pago de constancia",
                "estado" => "activo",
                "categoria" => 'todas',
                "prioridad_abono" => 1,
                "prioridad_por_antiguedad" => 1,
                "cargo_directo" => 1,
                "genera_iva" => 0,
                "abonable" => 0,
                "tarifa_fija" => 0,
            ],
            // Agrega más elementos aquí según sea necesario
        ];


        foreach ($conceptos as $concepto) {
            ConceptoCatalogo::factory()->create([
                'nombre' => ucfirst(strtolower($concepto["nombre"])),
                'descripcion' => ucfirst(strtolower($concepto["descripcion"])),
                'estado' => $concepto["estado"],
                "categoria" => $concepto["categoria"] ?? null,
                "tipo_tarifa" => $concepto["tipo_tarifa"] ?? null,
                'prioridad_abono' => $concepto["prioridad_abono"],
                'prioridad_por_antiguedad' => $concepto["prioridad_por_antiguedad"] ?? 0,
                'cargo_directo' => $concepto["cargo_directo"],
                'genera_iva' => $concepto["genera_iva"],
                'abonable' => $concepto["abonable"],
                'tarifa_fija' => $concepto["tarifa_fija"]
            ]);
        }
    }
}
